# Generated by Django 2.0.7 on 2018-09-19 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 15, 53, 36, 904925, tzinfo=utc)),
        ),
    ]
