# Generated by Django 2.0.7 on 2018-10-04 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0002_auto_20180919_1453'),
    ]

    operations = [
        UnaccentExtension(),
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 16, 53, 1, 544999, tzinfo=utc)),
        ),
    ]
