# Generated by Django 2.0.7 on 2018-10-22 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0003_auto_20181004_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 20, 17, 26, 576793, tzinfo=utc)),
        ),
    ]
