# Generated by Django 2.0.7 on 2018-10-22 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0004_auto_20181022_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 21, 9, 48, 706179, tzinfo=utc)),
        ),
    ]
