# Generated by Django 2.0.7 on 2018-07-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0005_auto_20180723_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='media/anonymous.mp4', upload_to='media/'),
        ),
    ]
