# Generated by Django 2.0.7 on 2018-10-24 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0006_auto_20181023_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 17, 14, 2, 821141, tzinfo=utc)),
        ),
    ]
