# Generated by Django 2.0.7 on 2018-07-23 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0007_auto_20180723_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='joinMe.Event'),
        ),
    ]
