# Generated by Django 2.0.7 on 2018-07-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0008_auto_20180723_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='media/anonymous.mp4', upload_to='videos/'),
        ),
    ]
