# Generated by Django 2.0.7 on 2018-11-13 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0011_auto_20181111_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 11, 17, 639057, tzinfo=utc)),
        ),
    ]
