# Generated by Django 2.0.7 on 2018-07-28 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0011_auto_20180728_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 23, 28, 32, 274776, tzinfo=utc)),
        ),
    ]
