# Generated by Django 2.0.7 on 2018-11-13 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0012_auto_20181113_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 18, 41, 18, 943508, tzinfo=utc)),
        ),
    ]
