# Generated by Django 2.0.7 on 2018-08-13 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0012_auto_20180728_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 13, 34, 27, 855659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(default='https://join-me.s3.amazonaws.com/input/video_.mov'),
        ),
    ]
