# Generated by Django 2.0.7 on 2018-08-18 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0013_auto_20180813_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_key',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 15, 40, 6, 43782, tzinfo=utc)),
        ),
    ]
