# Generated by Django 2.0.7 on 2018-11-13 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0013_auto_20181113_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 21, 33, 11, 813008, tzinfo=utc)),
        ),
    ]
