# Generated by Django 2.0.7 on 2018-11-14 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0014_auto_20181113_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 14, 9, 24, 963516, tzinfo=utc)),
        ),
    ]
