# Generated by Django 2.0.7 on 2019-05-05 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinMe', '0015_auto_20181114_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 5, 13, 49, 30, 908641, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guesttoevent',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'PENDING'), (3, 'SEEN'), (1, 'ACCEPTED'), (2, 'REFUSED')], default=0),
        ),
    ]
