# Generated by Django 2.0.7 on 2019-09-23 15:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('joinMe', '0017_auto_20190821_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stripe_id', models.CharField(default='', max_length=200)),
                ('plan', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GuestToVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.SmallIntegerField(choices=[(1, 'GOING'), (2, 'REFUSED')], default=0)),
                ('guest', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discount', models.CharField(blank=True, max_length=600)),
                ('followers', models.ManyToManyField(related_name='followed_page', to=settings.AUTH_USER_MODEL)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='venues', to='joinMe.Mood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_venues', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='venues', to='joinMe.Place')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 18, 41, 12, 978992, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='guesttovenue',
            name='venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='joinMe.Venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ManyToManyField(related_name='events', to='joinMe.Venue'),
        ),
    ]
